obs_detect_node:
  ros__parameters:
    spline_file_name: "/sim_ws/src/pure_pursuit_pkg/pure_pursuit_pkg/racelines/temp/spline.csv"
    coll_grid_topic: "/coll_grid_pub_rviz"
    coll_path_topic: "/coll_path_pub_rviz"
    use_avoid_topic: "/use_obs_avoid"
    gap_theta_topic: "/gap_thetas"
    scan_topic: "/scan"
    drive_topic: "/drive"
    pose_topic: "ego_racecar/odom"